Fix planning chart display in ddmrp_history
When displaying some buffers there is an error coming up from the
bokeh library:

    Error: invalid bbox {left: NaN, top: NaN, right: NaN, bottom: NaN}

And the planning chart is not displayed.

The error happens because max and min top are zeros.